# Event Processor - Prod 环境

aws:
  profile: prod-us
  region: us-west-2
  account_id: "879794963971"

app:
  name: event-processor-prod
  description: Event deduplication pipeline

flink:
  runtime: FLINK-1_20
  parallelism: 3
  parallelism_per_kpu: 1
  autoscaling_enabled: true
  min_parallelism: 3
  max_parallelism: 3

iam:
  # TODO: 更新为 prod 环境的 role
  execution_role_arn: arn:aws:iam::879794963971:role/lexi2-prod-usw2-879794963971-flink-execution-role

vpc:
  vpc_id: vpc-0a4f11f2a99810ac4
  subnet_ids:
    - subnet-08d26e6ce53fe8fe3
    - subnet-0009026f1574931c3
    - subnet-0198d157058ac5754
  security_group_id: sg-067dd2bc5db39db01

msk:
  bootstrap_servers: boot-obwbrb0l.c2.kafka-serverless.us-west-2.amazonaws.com:9098

s3:
  code_bucket: lexi2-prod-usw2-879794963971-flink-code

iceberg:
  warehouse: s3://dataware-landing-zone-prod/iceberg/
  database: raw_events_prod

kafka:
  input_topic: raw-events
  output_topic: processed-events
  attributed_topic: attributed-events
  partitions: 3  # Kafka 分区数，与 parallelism 一致

dynamodb:
  table_name: click_events_prod

logging:
  log_level: WARN
  log_group: /aws/kinesis-analytics/event-processor-prod
